minor_changes:
  - "Add new options ``--project``, ``--copyright``, ``--title``, ``--html-short-title``, and ``--extra-conf`` to the ``sphinx-init`` subcommand to allow to customize the generated ``conf.py`` Sphinx configuration (https://github.com/ansible-community/antsibull-docs/pull/77)."
