minor_changes:
  - "Improve build script generated by ``antsibull-docs sphinx-init`` to change to the directory where the script is located, instead of hardcoding the script's path. This also fixed the existing bug that the path was not quoted (https://github.com/ansible-community/antsibull-docs/issues/91, https://github.com/ansible-community/antsibull-docs/pull/92)."
